kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2017-03-18T19:14:38Z
  name: example-config
  namespace: default
data:
  PPORT: '9902'
  example2: world
  example3: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3