apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-bp
  labels:
    name: spring-bp
    version: latest
    visualize: "true"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: spring-bp
        app: spring-bp
        version: latest
        visualize: "true"
    spec:
      containers:
       - name: spring-bp
         image: kube-registry.kube-system.svc.cluster.local:31000/rak007007/gs-spring-boot
         imagePullPolicy: Always
         ports:
          - name: http
            containerPort: 8899
         env:
          - name: PPORT2
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PPORT
          - name: PPORT
            valueFrom:
              configMapKeyRef:
                name: example-config
                key: PPORT